import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated / third-party output (eslint on these is noise and very slow).
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    "storybook-static/**",
    // Vercel Workflow SDK route handlers (auto-generated by `withWorkflow()`).
    "src/app/.well-known/workflow/**",
    "app/.well-known/workflow/**",
  ]),
]);

export default eslintConfig;
