export { Hero } from "./Hero";
export type { HeroProps } from "./Hero";
export { HowItWorks } from "./HowItWorks";
export type { HowItWorksProps } from "./HowItWorks";
export { Features } from "./Features";
export type { FeaturesProps } from "./Features";
export { Pricing } from "./Pricing";
export type { PricingProps } from "./Pricing";
export { Footer } from "./Footer";
export type { FooterProps } from "./Footer";
