import { cn } from "@/lib/cn";
import { Badge } from "@/components/atoms/Badge";
import { Button } from "@/components/atoms/Button";
import { Card } from "@/components/atoms/Card";
import { MarkdownPreview } from "@/components/atoms/MarkdownPreview";
import {
  PostStatusBadge,
  type PostStatus,
} from "@/components/atoms/PostStatusBadge";

/**
 * Display shape for the article detail page. Mirrors `articles` minus
 * the columns the read view doesn't use (raw_ai_response, etc.).
 *
 * The connector loads the row server-side and converts it to this
 * shape so the organism stays a pure presentational component.
 */
export interface ArticleDetailData {
  id: string;
  title: string;
  /**
   * URL slug. Not displayed in the read view yet, but carried here so
   * the edit form (which IS controlled by this same data) can populate
   * its slug input without a second query.
   */
  slug: string | null;
  status: PostStatus;
  excerpt: string | null;
  metaDescription: string | null;
  targetKeyword: string | null;
  contentMarkdown: string | null;
  wordCount: number | null;
  generatedByModel: string | null;
  errorMessage: string | null;
  updatedAt: string;
  createdAt: string;
  /**
   * Numeric WordPress post id once the article has been pushed to a
   * connected WordPress site (always written together with
   * `wpPostUrl`). `null` means the article has not been sent yet —
   * the publish UI uses this to flip between "Send" and "Already
   * sent" modes.
   */
  wpPostId: number | null;
  /**
   * Public URL on the WordPress site. May be `null` even when
   * `wpPostId` is set (the WP REST response is allowed to omit
   * `link`).
   */
  wpPostUrl: string | null;
}

export interface ArticleDetailProps {
  article: ArticleDetailData;
  /** Triggered when the user clicks the Edit button. Omit to hide it. */
  onEdit?: () => void;
  className?: string;
}

function formatRelative(iso: string): string {
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return "";
  const diffMs = Date.now() - then;
  const minute = 60_000;
  const hour = 60 * minute;
  const day = 24 * hour;
  if (diffMs < minute) return "just now";
  if (diffMs < hour) return `${Math.floor(diffMs / minute)}m ago`;
  if (diffMs < day) return `${Math.floor(diffMs / hour)}h ago`;
  if (diffMs < 14 * day) return `${Math.floor(diffMs / day)}d ago`;
  return new Date(iso).toLocaleDateString();
}

export function ArticleDetail({
  article,
  onEdit,
  className,
}: ArticleDetailProps) {
  return (
    <article className={cn("space-y-6", className)}>
      <header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0 flex-1 space-y-2">
          <h1 className="text-2xl font-bold text-foreground sm:text-3xl">
            {article.title}
          </h1>
          <div className="flex flex-wrap items-center gap-2 text-xs text-muted">
            <PostStatusBadge status={article.status} />
            {article.targetKeyword ? (
              <Badge variant="default" size="sm">
                {article.targetKeyword}
              </Badge>
            ) : null}
            {article.wordCount ? (
              <span>~{article.wordCount.toLocaleString()} words</span>
            ) : null}
            {article.generatedByModel ? (
              <span>Generated by {article.generatedByModel}</span>
            ) : null}
            <span>Updated {formatRelative(article.updatedAt)}</span>
          </div>
        </div>
        {onEdit ? (
          <Button
            type="button"
            variant="primary"
            size="md"
            onClick={onEdit}
            className="shrink-0"
          >
            Edit
          </Button>
        ) : null}
      </header>

      {article.status === "failed" && article.errorMessage ? (
        <Card className="border-error/50 bg-error/5">
          <p className="text-sm font-semibold text-error">Generation failed</p>
          <p className="mt-1 text-sm text-error/80">{article.errorMessage}</p>
        </Card>
      ) : null}

      {article.excerpt ? (
        <Card>
          <h2 className="text-xs font-semibold uppercase tracking-wide text-muted">
            Excerpt
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-foreground">
            {article.excerpt}
          </p>
        </Card>
      ) : null}

      {article.metaDescription ? (
        <Card>
          <h2 className="text-xs font-semibold uppercase tracking-wide text-muted">
            Meta description
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-foreground">
            {article.metaDescription}
          </p>
        </Card>
      ) : null}

      <Card>
        <h2 className="text-xs font-semibold uppercase tracking-wide text-muted">
          Article body
        </h2>
        <div className="mt-3">
          {article.contentMarkdown && article.contentMarkdown.trim() ? (
            <MarkdownPreview markdown={article.contentMarkdown} />
          ) : (
            <p className="text-sm text-muted">
              No body yet.{" "}
              {article.status === "generating"
                ? "Generation is still in progress — refresh in a moment."
                : "Click Edit to add Markdown content."}
            </p>
          )}
        </div>
      </Card>
    </article>
  );
}
