import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { ArticleDetail, type ArticleDetailData } from "./ArticleDetail";

const baseArticle: ArticleDetailData = {
  id: "a1",
  title: "How to launch a B2B blog",
  slug: "how-to-launch-a-b2b-blog",
  status: "ready_for_review",
  excerpt: "A 30-day plan.",
  metaDescription: "Step-by-step playbook.",
  targetKeyword: "launch b2b blog",
  contentMarkdown: "# Heading\n\nBody paragraph.",
  wordCount: 1500,
  generatedByModel: "claude-sonnet-4-6",
  errorMessage: null,
  updatedAt: new Date("2026-05-07T15:00:00Z").toISOString(),
  createdAt: new Date("2026-05-07T14:00:00Z").toISOString(),
};

beforeEach(() => {
  vi.useFakeTimers();
  vi.setSystemTime(new Date("2026-05-07T15:30:00Z"));
});

afterEach(() => {
  cleanup();
  vi.useRealTimers();
});

describe("ArticleDetail", () => {
  it("renders the title, status badge, and key metadata", () => {
    render(<ArticleDetail article={baseArticle} />);
    expect(
      screen.getByRole("heading", { level: 1, name: baseArticle.title }),
    ).toBeInTheDocument();
    expect(screen.getByText(/Ready for review/i)).toBeInTheDocument();
    expect(screen.getByText("launch b2b blog")).toBeInTheDocument();
    expect(screen.getByText(/~1,500 words/)).toBeInTheDocument();
    expect(
      screen.getByText(/Generated by claude-sonnet-4-6/i),
    ).toBeInTheDocument();
    expect(screen.getByText(/Updated 30m ago/)).toBeInTheDocument();
  });

  it("renders the excerpt and meta description sections when present", () => {
    render(<ArticleDetail article={baseArticle} />);
    expect(screen.getByText("Excerpt")).toBeInTheDocument();
    expect(screen.getByText(baseArticle.excerpt!)).toBeInTheDocument();
    expect(screen.getByText("Meta description")).toBeInTheDocument();
    expect(screen.getByText(baseArticle.metaDescription!)).toBeInTheDocument();
  });

  it("hides the excerpt + meta description sections when null", () => {
    render(
      <ArticleDetail
        article={{ ...baseArticle, excerpt: null, metaDescription: null }}
      />,
    );
    expect(screen.queryByText("Excerpt")).not.toBeInTheDocument();
    expect(screen.queryByText("Meta description")).not.toBeInTheDocument();
  });

  it("hides the metadata bits that aren't present (target keyword, word count, model)", () => {
    render(
      <ArticleDetail
        article={{
          ...baseArticle,
          targetKeyword: null,
          wordCount: null,
          generatedByModel: null,
        }}
      />,
    );
    expect(
      screen.queryByText(baseArticle.targetKeyword!),
    ).not.toBeInTheDocument();
    expect(screen.queryByText(/words/)).not.toBeInTheDocument();
    expect(screen.queryByText(/Generated by/)).not.toBeInTheDocument();
  });

  it("renders the markdown body via MarkdownPreview", () => {
    render(<ArticleDetail article={baseArticle} />);
    // The h1 from the MarkdownPreview is rendered inside the body card.
    expect(
      screen.getByRole("heading", { level: 1, name: /Heading/ }),
    ).toBeInTheDocument();
    expect(screen.getByText(/Body paragraph/)).toBeInTheDocument();
  });

  it("renders the empty body fallback for an article without a body", () => {
    render(
      <ArticleDetail
        article={{
          ...baseArticle,
          contentMarkdown: null,
          status: "draft",
        }}
      />,
    );
    expect(screen.getByText(/No body yet\./i)).toBeInTheDocument();
    expect(screen.getByText(/Click Edit/i)).toBeInTheDocument();
  });

  it("shows the in-progress hint when an empty article is still generating", () => {
    render(
      <ArticleDetail
        article={{
          ...baseArticle,
          contentMarkdown: null,
          status: "generating",
        }}
      />,
    );
    expect(
      screen.getByText(/Generation is still in progress/i),
    ).toBeInTheDocument();
  });

  it("renders the failure card when status is failed and an error exists", () => {
    render(
      <ArticleDetail
        article={{
          ...baseArticle,
          status: "failed",
          errorMessage: "Anthropic API timed out.",
        }}
      />,
    );
    expect(screen.getByText("Generation failed")).toBeInTheDocument();
    expect(screen.getByText("Anthropic API timed out.")).toBeInTheDocument();
  });

  it("hides the failure card when status is failed but error_message is null", () => {
    render(
      <ArticleDetail
        article={{
          ...baseArticle,
          status: "failed",
          errorMessage: null,
        }}
      />,
    );
    expect(screen.queryByText("Generation failed")).not.toBeInTheDocument();
  });

  it("renders the Edit button when onEdit is provided", () => {
    const onEdit = vi.fn();
    render(<ArticleDetail article={baseArticle} onEdit={onEdit} />);
    fireEvent.click(screen.getByRole("button", { name: /^edit$/i }));
    expect(onEdit).toHaveBeenCalledOnce();
  });

  it("hides the Edit button when onEdit is omitted", () => {
    render(<ArticleDetail article={baseArticle} />);
    expect(
      screen.queryByRole("button", { name: /^edit$/i }),
    ).not.toBeInTheDocument();
  });

  it("forwards a custom className to the root", () => {
    const { container } = render(
      <ArticleDetail article={baseArticle} className="custom-cls" />,
    );
    expect(container.firstChild).toHaveClass("custom-cls");
  });

  it("renders 'just now' for updates under a minute old", () => {
    render(
      <ArticleDetail
        article={{
          ...baseArticle,
          updatedAt: new Date("2026-05-07T15:29:30Z").toISOString(),
        }}
      />,
    );
    expect(screen.getByText(/Updated just now/)).toBeInTheDocument();
  });

  it("renders hours ago for updates under a day old", () => {
    render(
      <ArticleDetail
        article={{
          ...baseArticle,
          updatedAt: new Date("2026-05-07T11:00:00Z").toISOString(),
        }}
      />,
    );
    expect(screen.getByText(/Updated 4h ago/)).toBeInTheDocument();
  });

  it("renders days ago for updates under two weeks old", () => {
    render(
      <ArticleDetail
        article={{
          ...baseArticle,
          updatedAt: new Date("2026-05-04T15:30:00Z").toISOString(),
        }}
      />,
    );
    expect(screen.getByText(/Updated 3d ago/)).toBeInTheDocument();
  });

  it("falls back to a locale date for updates older than two weeks", () => {
    render(
      <ArticleDetail
        article={{
          ...baseArticle,
          updatedAt: new Date("2026-04-15T15:30:00Z").toISOString(),
        }}
      />,
    );
    expect(screen.getByText(/Updated /)).toBeInTheDocument();
  });

  it("renders an empty time fragment for an invalid updatedAt", () => {
    // Should not crash; the metadata row still renders.
    render(
      <ArticleDetail article={{ ...baseArticle, updatedAt: "not-a-date" }} />,
    );
    expect(
      screen.getByRole("heading", { level: 1, name: baseArticle.title }),
    ).toBeInTheDocument();
  });
});
