-- ============================================================================
-- article_image_uploads — section-image columns
--
-- Forward-compatibility for the future "image above each H2 section"
-- editor flow. v3 only writes `'featured'` rows; this migration adds
-- the columns + indexes so v4 can land the section-image UI without
-- another schema PR.
--
--   * `section_key` — stable, slugified id derived from the section's
--     H2 heading text. Generated by the new
--     `lib/extract-article-sections.ts` parser, so the editor and the
--     section-image picker agree on which key belongs to which H2.
--     Null for `role = 'featured'` rows.
--
--   * `section_heading` — the human-readable H2 text, stored alongside
--     the key so we can render the picker without re-parsing the
--     Markdown body. Null for featured rows.
--
--   * `sort_order` — per-article ordering. Featured rows default to 0;
--     section rows take their `sortOrder` from the parser (0 = first
--     H2 in the body). Indexed below for fast `ORDER BY` reads.
--
-- We keep `role` as free-form `text` (not a check constraint) so adding
-- future roles like `'inline'`, `'cover'`, `'og'` doesn't require
-- another migration. The TypeScript layer pins the known values.
--
-- Indexes:
--   * `(article_id, sort_order)` — the section-image picker reads
--     "all images for this article ordered by sort_order" on every
--     editor open.
--   * `(article_id, role)` — keeps "all featured rows for this
--     article" / "all section rows for this article" lookups fast
--     once we have a mix of roles per article.
-- ============================================================================

alter table public.article_image_uploads
  add column if not exists section_key text,
  add column if not exists section_heading text,
  add column if not exists sort_order integer not null default 0;

create index if not exists article_image_uploads_article_id_sort_order_idx
  on public.article_image_uploads(article_id, sort_order);
create index if not exists article_image_uploads_article_id_role_idx
  on public.article_image_uploads(article_id, role);
