import type { Meta, StoryObj } from "@storybook/react";
import { StatCard } from "./StatCard";

const meta = {
  title: "Molecules/StatCard",
  component: StatCard,
  parameters: { layout: "padded" },
  tags: ["autodocs"],
  argTypes: {
    tone: {
      control: "select",
      options: ["default", "brand", "success", "warning", "error"],
    },
  },
} satisfies Meta<typeof StatCard>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: { label: "Total posts", value: 42, hint: "Across all destinations" },
};

export const Brand: Story = {
  args: { label: "Published", value: 21, tone: "brand", hint: "+3 this week" },
};

export const Warning: Story = {
  args: {
    label: "Awaiting review",
    value: 4,
    tone: "warning",
    hint: "Oldest 2 days",
  },
};

export const Error: Story = {
  args: {
    label: "Failed jobs",
    value: 2,
    tone: "error",
    hint: "Last failed 12m ago",
  },
};

export const Grid: Story = {
  args: { label: "Total posts", value: 42 },
  render: () => (
    <div className="grid w-[800px] grid-cols-2 gap-4 md:grid-cols-4">
      <StatCard label="Total posts" value={42} />
      <StatCard label="Drafts" value={5} hint="3 generated by AI" />
      <StatCard
        label="Scheduled"
        value={8}
        tone="brand"
        hint="Next at 9:00 AM"
      />
      <StatCard label="Published" value={29} tone="success" />
    </div>
  ),
};
